@startuml classDiagramm-SimplyList
class Node{
    int data
    Node next
}
class LinkedList{
    Node head
    Node tail

    Node getHead()
    Node getTail()
    void printNode()
    void printAll()
    void addFirst()
    void addLast()
    Node executeFirst()
    Node executeLast()
    boolean isContain()
    boolean isEmpty()
    void printAll()
    void deleteByValue()
}
Node --* LinkedList : contains

@enduml