@startuml classDiagramm-DoublyList
title DoublyList class diagram

class SimplyNode{
    int data
    Node forvard
}
class DoublyNode{
    int data
    Node forvard
    Node backward
}
class SimplyList{
    Node head
    Node tail
    boolean isEmpty()
    void addFirst()
    void addLast()
    void printNode()
    void printAll()
    Node getHead()
    Node getTail()
    void setHead()
    void setTail()
    Node executeFirst()
    Node executeLast()
    boolean isContain()
    void deleteByValue()
}
class DoublyList{
    Node head
    Node tail
    boolean isEmpty()
    void addFirst()
    void addLast()
    void printNode()
    void printAll()
    Node getHead()
    Node getTail()
    void setHead()
    void setTail()
    Node executeFirst()
    Node executeLast()
    boolean isContain()
    void deleteByValue()
    void arrayToHead()
    void arrayToTail()
    void collectionToHead()
    void collectionToTail()
    void absorptionToHead()
    void absorptionToTail()
    void printForvard()
    void printBackvard()
}
enum Math{
    INCREASE
    DeCREASE
}
DoublyList *--  DoublyNode : "Список (list) \n состоит из узлов (node)"
DoublyList *-- Math :"Список содержит \n перечисление математических операций"
SimplyList *-- SimplyNode : "Список (list) \n состоит из узлов (node)"
DoublyList -->  SimplyList : "Наследуется, \n переопределяет часть методов"
DoublyNode --> SimplyNode : "Наследуется"
@enduml