@startuml sequence
data -> temp : first value
temp -> head : first value
temp -> tail : first value
data --> temp : second value
temp --> head : second value
head --> second : first value
data --> temp : therd value
temp --> head : therd value
head --> therd : therd value

@enduml